### ISSUE TITLE
Register arrays for registers with fields longer than 32 bit fail

### ISSUE THREAD

**Issue by AndreasKarg** [rust-embedded/svdtools#58]
I have a peripheral with a number of registers, each 64 bits long. Within each register is one 40 bit long field.
Trying to merge these registers into an array fails with the following error message:
```.venv/bin/svd patch example/incomplete-stm32l4x2.yaml
Traceback (most recent call last):
  File ".venv/bin/svd", line 8, in <module>
    sys.exit(svdtools_cli())
  File "/mnt/btrfs/svdtools/.venv/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/btrfs/svdtools/.venv/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/mnt/btrfs/svdtools/.venv/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/btrfs/svdtools/.venv/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/btrfs/svdtools/.venv/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/mnt/btrfs/svdtools/.venv/lib/python3.8/site-packages/svdtools/cli.py", line 16, in patch
    svdtools.patch.main(yaml_file)
  File "/mnt/btrfs/svdtools/.venv/lib/python3.8/site-packages/svdtools/patch.py", line 1332, in main
    process_device(svd, root)
  File "/mnt/btrfs/svdtools/.venv/lib/python3.8/site-packages/svdtools/patch.py", line 1309, in process_device
    d.process_peripheral(periphspec, device[periphspec], update_fields)
  File "/mnt/btrfs/svdtools/.venv/lib/python3.8/site-packages/svdtools/patch.py", line 665, in process_peripheral
    p.collect_in_array(rspec, rmod)
  File "/mnt/btrfs/svdtools/.venv/lib/python3.8/site-packages/svdtools/patch.py", line 878, in collect_in_array
    bitmasks = [Register(r[0]).get_bitmask() for r in registers]
  File "/mnt/btrfs/svdtools/.venv/lib/python3.8/site-packages/svdtools/patch.py", line 878, in <listcomp>
    bitmasks = [Register(r[0]).get_bitmask() for r in registers]
  File "/mnt/btrfs/svdtools/.venv/lib/python3.8/site-packages/svdtools/patch.py", line 1259, in get_bitmask
    mask |= (0xFFFFFFFF >> (32 - fwidth)) << foffset
ValueError: negative shift count
make: *** [Makefile:12: example] Error 1
```

I have created a minimum failing example that fits neatly into the example from the repo:
```
_add:
  EXAMPLE:
    registers:
      REG0:
        addressOffset: "0x0000000"
        size: 0x40
        fields:
          FIELD:
            bitOffset: 0
            bitWidth: 33
      REG1:
        addressOffset: "0x0000008"
        size: 0x40
        fields:
          FIELD:
            bitOffset: 0
            bitWidth: 33

EXAMPLE:
  _array:
    REG*: {}
```

I have played around a bit, and the patch seems to generate fine as long as the field is shorter than 32 bits, even if I offset it into the top half of the register.

(Found on v0.1.13)

**Comment by burrbull** [comment]
Should be fixed. Reopen if it is not.
